#!/usr/bin/env bash
# Installs HAProxy version 1.8 with the following configurations:
#+    Enables management via the init script.
#+    Distributes requests using a round-robin algorithm.

sudo apt update
sudo apt upgrade

sudo apt install software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.5
sudo apt update
sudo apt install haproxy

echo "ENABLED=1" >> /etc/default/haproxy
mv /etc/haproxy/haproxy.cfg{,.original}
touch /etc/haproxy/haproxy.cfg

printf %s "global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy

defaults
    log     global
    mode    HTTP
    option http-keep-alive
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    timeout connect  5000
    timeout client  10000
    timeout server  10000

listen hbnb
    bind 0.0.0.0:80
    mode http
    stats enable
    stats uri /haproxy?stats
    balance roundrobin
    option httpclose
    option forwardfor
    server 312760-web-01 34.227.91.107:80 check
    server 312760-web-02 100.25.154.95:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
