#!/usr/bin/env bash
# Bash script that listens on port 98 on localhost

# Check if the script is executed with root privileges
if [[ $(id -u) -ne 0 ]]; then
  echo "This script must be run as root. Use sudo or run as root."
  exit 1
fi

# Start the netcat server listening on port 98
netcat -l -p 98